const currency = "₹"
const metricTypes = [
    {name: "Total Sales", description: "Equates to gross sales - discounts - returns + taxes + shipping charges.", prefix: `${currency}`, suffix: ""},
    {name: "Taxes", description: "The total amount of taxes charged on orders during this period.", prefix: `${currency}`, suffix: ""},
    {name: "Net Sales", description: "Equates to gross sales + shipping - taxes - discounts - returns.", prefix: `${currency}`, suffix: ""},
    // {name: "Returns", description: "The value of goods returned by a customer."},
    {name: "COGS", description: "Equates to Product Costs + Shipping Costs + Fulfillment Costs + Packing Fees + Transaction Fees", prefix: `${currency}`, suffix: ""},
    {name: "COGS %", description: "Cost of Goods (COGS) as % of Net Sales", prefix: "", suffix: "%"},
    // {name: "Shipping Paid", description: "Shipping paid by customers as part of orders during this period."},
    // {name: "Shipping Cost", description: "The shipping cost paid by you to shipping providers. This amount is set under"},
    // {name: "Transaction Fees", description: "Card processing fees paid by customers as part of the order process. Includes FX fees charged by your payment processor for International Cards. Update under"},
    // {name: "Fulfillment Costs", description: "Cost of Fulfillment Pick & Pack Fees"},
    {name: "Gross Profit", description: "Calculated by subtracting Cost of Goods (COGS) from Net Sales.", prefix: `${currency}`, suffix: ""},
    {name: "Gross Profit %", description: "Gross Profit as a % of Net Sales", prefix: "", suffix: "%"},
    // {name: "Contribution Margin", description: "Net sales - COGS - Marketing Costs = Contribution Margin"},
    // {name: "Contribution Margin %", description: "Contribution Margin as a % of Net Sales"},
    // {name: "New Customer Contribution Margin", description: "The contribution margin (gross profit after marketing costs) you've earned from new customers. Keeping this above 0 means you are first order profitable. New Customer Net Sales - New Customer COGS - Total Marketing Spend"},
    // {name: "Operational Expenses", description: "Costs related to the operation of the business that aren’t directly tied to producing goods or services (e.g., rent, utilities, salaries). Add under Other Costs"},
    // {name: "Operational Expenses %", description: "Operating Expenses as % of Net Sales"},
    // {name: "Net Profit", description: "Net Sales - COGS - Marketing Costs - Operating Expenses = Net Profit"},
    // {name: "Net Profit %", description: "Net Profit as a % of Net Sales"},
    // {name: "Staff Cost %", description: "The cost of Staff inputted under the Staff Settings tab as a % of Net Sales"},
    {name: "Orders", description: "Number of orders", prefix: "", suffix: ""},
    {name: 'New Customer Orders', description: 'Number of orders from new customers', prefix: "", suffix: ""},
    // {name: "Total Ad Spend", description: "The total cost of paid advertising across connected channels during this period."},
    // {name: "Marketing %", description: "Marketing Costs (Ad Spend and Marketing Categorised Expenses) as a % of net sales. (Ad Spend+Marketing Expenses)/Net Sales"},
    // {name: "Total Sales MER", description: "Marketing Efficiency Ratio | Total return on your total marketing spend. | Net Sales / Marketing Spend"},
    // {name: "MER", description: "Marketing Efficiency Ratio | Total return on your total marketing spend. | Net Sales / Marketing Spend"},
    // {name: "BEP MER", description: "Breakeven Ratio of Marketing Spend | The minimum return on your marketing spend needed to break even. | Net Sales - COGS - Operating Expenses = Breakeven Marketing Spend | Gross Profit / Breakeven Marketing Spend = BEP MER"},
    // {name: "BEP ROAS", description: "The minimum ROAS (Return on Ad Spend) needed to cover your cost of goods. Net Sales / ( Net Sales – Total cost of goods) = Breakeven ROAS"},
    // {name: "Cost Per Acquisition", description: "The total cost to Acquire a New Customer. Ad Spend + Marketing Spend / Number of New Customers."},
    // {name: "New Customer Acquisition Cost", description: "Cost to Acquire a New Customer. Ad Spend + Marketing Spend / Number of New Customers."},
    // {name: "Acquisition MER", description: "Ratio of new customer revenue to ad spend. This metrics tells us how efficiently you're turning ad spend into revenue from new customers. Total New Customer Revenue / Total Ad Spend"},
    {name: "New Customers", description: "The number of first-time buyers during a specific period.", prefix: "", suffix: ""},
    {name: "Repeat Customers", description: "Customers who have made more than one purchase in their order history.", prefix: "", suffix: ""},
    {name: "New Customer Sales", description: "Net Sales generated from new customers during this time period.", prefix: `${currency}`, suffix: ""},
    {name: "Repeat Customer Sales", description: "Net Sales generated from existing customers during this time period.", prefix: `${currency}`, suffix: ""},
    // {name: "Gross Profit Per New Customer", description: "New Customer Net Sales - New Customer COGS."},
    // {name: "Gross Profit Per Repeat Customer", description: "Repeat Customer Net Sales - Repeat Customer COGS."},
    {name: "New Customer AOV", description: "Average Value of Each Order from a New Customer. Total New Customer Sales / Number of New Customers.", prefix: `${currency}`, suffix: ""},
    {name: "Repeat Customer AOV", description: "Average Value of Each Order from a Repeat Customer. Total Repeat Customer Sales / Number of Repeat Customers.", prefix: `${currency}`, suffix: ""},
    {name: "AOV", description: "Average Value of Each Order Total Sales / Orders", prefix: `${currency}`, suffix: ""},
    {name: "Average No Of Items", description: "The average number of items per order. | Total Items Ordered / Total Orders.", prefix: "", suffix: ""},
    {name: "Total Customers", description: "The total number of unique customers who have made a purchase.", prefix: "", suffix: ""}
];